package pt.ulusofona.copelabs.oi_ndn.presenters;

import android.app.Activity;

import pt.ulusofona.copelabs.oi_ndn.helpers.Preferences;
import pt.ulusofona.copelabs.oi_ndn.interfaces.UserConfigurationContract;
import pt.ulusofona.copelabs.oi_ndn.models.Contact;

/**
 * This class is part of Oi application.
 * It receives the interactions from the UserConfigurationActivity class and performs the actions based on
 * those interactions.
 *
 * @author Omar Aponte (COPELABS/ULHT)
 * @version 1.0
 *          COPYRIGHTS COPELABS/ULHT, LGPLv3.0, 02/14/18
 */
public class UserConfigurationPresenter implements UserConfigurationContract.Presenter {

    /**
     * Variable that specifies that the activity was initialized from the UserSelectionActivity class.
     */
    private static final String FROM_USER_SELECTION_ACTIVITY = "1";

    /**
     * View interface implemented by the activity.
     */
    private UserConfigurationContract.View mView;

    /**
     * Activity variable.
     */
    private Activity mActivity;

    /**
     * This variable contains information about from which activity was
     * initialized the UserConfiguration activity.
     */
    private String mFromActivity;

    /**
     * Constructor of UserConfigurationPresenter class.
     * @param view View interface implemented by the activity.
     * @param activity Activity variable.
     * @param fromActivity information about from which activity was
     * initialized the UserConfiguration activity.
     */
    public UserConfigurationPresenter(UserConfigurationContract.View view, Activity activity, String fromActivity) {
        mView = view;
        mActivity = activity;
        mFromActivity = fromActivity;
        start();
    }

    /**
     * Start the inital configuration of the view.
     * Send contact information to the view and hide
     * error messages.
     */
    @Override
    public void start() {
        Contact contact = Preferences.getLocalContact(mActivity);
        mView.showContactInformation(contact.getName(), contact.getID());
        mView.hidePhoneNumberErrorMessage();
        mView.hideUserNameErrorMessage();
    }

    /**
     * Uses the parameters sent by the view and save the information about de user in preferences.
     * if user's name or phone number field are empty an error message is shown.
     *
     * @param name        String user name.
     * @param phoneNumber String phone number.
     */
    @Override
    public void onFormFilled(String name, String phoneNumber) {
        if (name.equals("")) {
            mView.showUserNameErrorMessage();
            mView.disableSaveButton();
        } else
            mView.hideUserNameErrorMessage();

        if (phoneNumber.equals("")) {
            mView.showPhoneNumberErrorMessage();
            mView.disableSaveButton();
        } else
            mView.hidePhoneNumberErrorMessage();

        if (!name.equals("") && !phoneNumber.equals("")) {
            Contact contact = new Contact(phoneNumber, name);
            Preferences.saveLocalContact(mActivity, contact);
            if (mFromActivity.equals(FROM_USER_SELECTION_ACTIVITY))
                mView.startEndUserActivity();
            else
                mView.finishActivity();
        }
    }

    /**
     * Hides the error message generated by user name field empty. This action occur when hte user
     * introduces values in the user name field.
     *
     * @param length Integer length of the text in the editText.
     */
    @Override
    public void userNameEditTxtChanged(int length) {
        if (length > 0) {
            mView.hideUserNameErrorMessage();
            mView.enableSaveButton();
        }
    }

    /**
     * Hides the error message generated by user's phone number field empty. This action occur when
     * the user introduces values in the phone number field.
     *
     * @param length Integer length of the text in the editText.
     */
    @Override
    public void phoneNumberEditTxtChanged(int length) {
        if (length > 0) {
            mView.hidePhoneNumberErrorMessage();
            mView.enableSaveButton();
        }
    }


}
