package pt.ulusofona.copelabs.oi.presenters;

import android.Manifest;
import android.app.Activity;
import android.content.Context;
import android.support.v4.app.ActivityCompat;
import android.support.v4.content.ContextCompat;

import pt.ulusofona.copelabs.oi.activities.UserConfigurationActivity;
import pt.ulusofona.copelabs.oi.helpers.Preferences;
import pt.ulusofona.copelabs.oi.interfaces.UserConfigurationContract;
import pt.ulusofona.copelabs.oi.models.Contact;

/**
 * This class is part of Oi application.
 * It receives the interactions from the UserConfigurationActivity class and performs the actions based on
 * those interactions.
 *
 * @author Omar Aponte (COPELABS/ULHT)
 * @version 1.0
 *          COPYRIGHTS COPELABS/ULHT, LGPLv3.0, 02/14/18
 */
public class UserConfigurationPresenter implements UserConfigurationContract.Presenter {

    /**
     * Variable that specifies that the activity was initialized from the UserSelectionActivity class.
     */
    private static final String FROM_USER_SELECTION_ACTIVITY = "1";

    /**
     * View interface implemented by the activity.
     */
    private UserConfigurationContract.View mView;

    /**
     * Activity variable.
     */
    private Activity mActivity;

    /**
     * This variable contains information about from which activity was
     * initialized the UserConfiguration activity.
     */
    private String mFromActivity;

    /**
     * Context of the application.
     */
    private Context mContext;

    /**
     * Variable used to identify the permission of location.
     */
    private static final int MY_PERMISSIONS_REQUEST_ACCESS_LOCATION = 2;

    /**
     * Constructor of UserConfigurationPresenter class.
     * @param view View interface implemented by the activity.
     * @param activity Activity variable.
     * @param fromActivity information about from which activity was
     * initialized the UserConfiguration activity.
     */
    public UserConfigurationPresenter(UserConfigurationContract.View view, Activity activity, String fromActivity, Context context) {
        mView = view;
        mActivity = activity;
        mFromActivity = fromActivity;
        mContext=context;
        start();
    }

    /**
     * Start the inital configuration of the view.
     * Send contact information to the view and hide
     * error messages.
     */
    @Override
    public void start() {
        if(mFromActivity.equals(UserConfigurationActivity.FROM_USER_SELECTION_ACTIVITY)) {
            mView.showActivityContuntryCode();
            checkLocationPermission();
        }
        else {
            mView.showDefaultActivity();
        }
        Contact contact = Preferences.getLocalContact(mActivity);
        mView.showContactInformation(contact.getName(), contact.getID());
        mView.hidePhoneNumberErrorMessage();
        mView.hideUserNameErrorMessage();
    }

    /**
     * Uses the parameters sent by the view and save the information about de user in preferences.
     * if user's name or phone number field are empty an error message is shown.
     *
     * @param name        String user name.
     * @param phoneNumber String phone number.
     */
    @Override
    public void onFormFilled(String name, String phoneNumber) {
        if (name.equals("")) {
            mView.showUserNameErrorMessage();
            mView.disableSaveButton();
        } else
            mView.hideUserNameErrorMessage();

        if (phoneNumber.equals("")) {
            mView.showPhoneNumberErrorMessage();
            mView.disableSaveButton();
        } else
            mView.hidePhoneNumberErrorMessage();

        if (!name.equals("") && !phoneNumber.equals("")) {
            Contact contact = new Contact(phoneNumber, name);
            Preferences.saveLocalContact(mActivity, contact);
            if (mFromActivity.equals(FROM_USER_SELECTION_ACTIVITY))
                mView.startEndUserActivity();
            else
                mView.finishActivity();
        }
    }

    /**
     * Hides the error message generated by user name field empty. This action occur when hte user
     * introduces values in the user name field.
     *
     * @param length Integer length of the text in the editText.
     */
    @Override
    public void userNameEditTxtChanged(int length) {
        if (length > 0) {
            mView.hideUserNameErrorMessage();
            mView.enableSaveButton();
        }
    }

    /**
     * Hides the error message generated by user's phone number field empty. This action occur when
     * the user introduces values in the phone number field.
     *
     * @param length Integer length of the text in the editText.
     */
    @Override
    public void phoneNumberEditTxtChanged(int length) {
        if (length > 0) {
            mView.hidePhoneNumberErrorMessage();
            mView.enableSaveButton();
        }
    }

    /**
     * Function used to check the location permission.
     * @return Boolean, where true value mean the the permission is granted, otherwise, false.
     */
    private boolean checkLocationPermission() {
        boolean result = true;
        int permissionCheck = ContextCompat.checkSelfPermission(mContext,
                Manifest.permission.ACCESS_FINE_LOCATION);
        int permissionCheck1 = ContextCompat.checkSelfPermission(mContext,
                Manifest.permission.ACCESS_COARSE_LOCATION);
        if (permissionCheck == -1 && permissionCheck1 == -1) {
            ActivityCompat.requestPermissions(mActivity, new String[]{Manifest.permission.ACCESS_COARSE_LOCATION,Manifest.permission.ACCESS_FINE_LOCATION}, MY_PERMISSIONS_REQUEST_ACCESS_LOCATION);
            result = false;
        }
        return result;
    }

}
